### ISSUE TITLE
Extract silent parts only

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#14]
https://github.com/antiboredom/videogrep/issues/69
here is links
https://www.youtube.com/watch?v=qEtEbXVbYJQ
How do I extract all silent parts?

**Comment by kelciour** [comment]
python -mvideogrep.silence --input input.mp4

**Comment by raj6996** [comment]
```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Python38\Lib\site-packages\videogrep\videogrep.py", line 14, in <module>
    from .vtt import parse_auto_sub
ImportError: attempted relative import with no known parent package

```

**Comment by kelciour** [comment]
Maybe try to reinstall it with `python -m pip install --upgrade --no-deps --force-reinstall videogrep`

**Comment by raj6996** [comment]
Ok, thanks it works, is there anyway to use your playphrase?

**Comment by kelciour** [comment]
No.
