### ISSUE TITLE
English Words okay, Non native language not works

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#20]
```
Ok@DESKTOP-7J7A2A6 MINGW64 /d/playphrase-v1.2.9-win64
$ ./playphrase -i "D:\English\New folder" -o "D:\English\New folder\Here" -v -s "मटका"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "subprocess.py", line 1366, in _readerthread
  File "c:\users\nickolay\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 97: character maps to <undefined>
Traceback (most recent call last):
  File "playphrase.py", line 594, in <module>
  File "playphrase.py", line 290, in main
  File "subprocess.py", line 1024, in communicate
  File "subprocess.py", line 1416, in _communicate
IndexError: list index out of range
[3580] Failed to execute script playphrase

Ok@DESKTOP-7J7A2A6 MINGW64 /d/playphrase-v1.2.9-win64
$
```
Everything works fine my laptop, I just installed python 3.9  win64 on Win10 Desktop, and I was getting this error with hindi words, but English words works fine. Can you take a look into it.

**Comment by kelciour** [comment]
Try to set to UTF-8.

![image](https://user-images.githubusercontent.com/16260735/96930117-dd5d7580-14c3-11eb-983b-0b24c2ec115a.png)

**Comment by raj6996** [comment]
yes did it before you posted that screenshot.
Nothing works, that quite strange for me.
Laptop Python 3.8.6 x64, Gitbash v2.28.0
Desktop python 3.9 x64, Gitbash v2.29
Maybe I should revert to check it works on desktop.

**Comment by kelciour** [comment]
Try to type `locale`. What does it say?

![image](https://user-images.githubusercontent.com/16260735/96945847-7a7dd580-14e7-11eb-8b95-4bd42b9b153b.png)

I'll add a possible fix tomorrow to force UTF-8 but don't know if it'll work or not.

**Comment by raj6996** [comment]
haha, I checked language settings of gitbash in the Laptop . I was wondering it was selected as hi-IN, Now I installed hindi language and gitbash shows it. and it works in desktop. thanks for fast reply and help.
